version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: golang
    versions:
    - 1.14.14.pre.stretch
    - 1.14.15.pre.stretch
    - 1.16.0.pre.stretch
    - 1.16.1.pre.stretch
    - 1.16.2.pre.stretch
